### ISSUE TITLE
"apply" button always greyed out

### ISSUE THREAD

**Issue by pat-s** [nwg-piotr/azote#1]
Using sway-git. 
Hence I can't apply any wallpaper.

Thanks for the app!

**Comment by nwg-piotr** [comment]
v0.0.2 is almost ready, should be available in less than half an hour. Please let me know if it resolves the issue.

**Comment by pat-s** [comment]
Thanks, works now!

**Comment by nwg-piotr** [comment]
Thanks for reporting. I'd be grateful for further testing.
