### ISSUE TITLE
Application name not visible in gnome3 menu

### ISSUE THREAD

**Issue by jubalh** [nwg-piotr/azote#100]
If I understand https://python-gtk-3-tutorial.readthedocs.io/en/latest/application.html correctly then you should use `Gtk.Application` and `Gtk.ApplicationWindow()` to fix this.

AFAIK the title of the application gets taken from the shipped desktop file, but only if this is an `Gtk.Application`.

I'm aware this project is geared towards i3 (etc) but I guess this is generally worth improving.

**To Reproduce**
1. Open azote under gnome3
2. Look at menubar
4.  You see `main.py` instead of `azote~`

**Expected behavior**
See the applications name.

**Screenshots**
![az1](https://user-images.githubusercontent.com/1658215/88937425-6d54a000-d284-11ea-9edb-0fe801068dfd.png)

**Desktop (please complete the following information):**
 - Linux distribution: openSUSE
 - WM: gnome3

**Azote version (please state it clearly if you use -git version):**
1.7.12

**Comment by nwg-piotr** [comment]
LOL, I haven't used gnome for about 2 years, and no idea if Azote is even going to work there :) 

I'll try to setup gnome on my testing laptop, or borrow my daughters one, and take a closer look at this.

**Comment by nwg-piotr** [comment]
Due to use of the `wlr-randr` command, Azote no longer starts on GNOME, which is officially unsupported from now on.
