### ISSUE TITLE
Allow graceful failures with helpful messages when optional dependencies are missing

### ISSUE THREAD

**Issue by ahesford** [nwg-piotr/azote#101]
It looks like you print some useful messages when optional dependencies like `send2trash` are not found. Please make sure that all of your optional dependencies provide clear failures when attempting to access features that require them, providing users with hints about what needs to be installed.

Also note that `xrandr` should be optional, because it is only useful or required when not running `sway`.

The motiviation is to clean up your Void template, which pulls in all of the optional dependencies but shouldn't---if a user has a pure Wayland setup, the `xrandr` dependency pulls in several X libraries; conversely, if the user has a simple X11 setup, `grim` and `slurp` dependencies will pull in wayland and a bunch of libraries that may not be desired.

If `azote` provides clear messages when it finds each optional package missing, the Void template can be simplified and only pull in the core dependencies. (It would be nice if Void supported optional dependencies, but that's a discussion for another time...)

**Comment by nwg-piotr** [comment]
Well, I must admit that Void templates are usually PITA to me. :)

If it comes to dependencies: I remember having difficulties while trying to get rid of obligatory `xrandr` dependency. No more details at the moment.

I'll take into account missing dependency warnings in further development.

**Comment by nwg-piotr** [comment]
For missing dependencies, that are critical in detected environment, I added messages and `exit(1)`. Presence of those, which are really optional will still be logged to ~/.local/share/azote/log.txt` only. This resolves the issue in Arch Linux, but not in Void. The latter would need split Wayland and X11 packages.

It would be great if someone else could take care of packaging Azote for Void.
