### ISSUE TITLE
Azote fails to start

### ISSUE THREAD

**Issue by oscarcp** [nwg-piotr/azote#102]
**Describe the bug**
Azote fails to start due to `scr_path` (tools.py:441) returning `None`  (programmer comment. You have a typo in the variable, although you followed up with the typo, you should correct it! :D)

**To Reproduce**
1. Start azote (from terminal or launcher)

**Expected behavior**
Azote should start and allow wallpaper changes.

**Screenshots**
![2020-08-02-12:17:26-screenshot](https://user-images.githubusercontent.com/462631/89120903-349e0c00-d4ba-11ea-99a3-2569484bb67f.png)

Transcript:
```
main.py:744: DeprecationWarning: Gdk.Screen.height is deprecated
  h = screen.height()
Traceback (most recent call last):
  File "main.py", line 1812, in <module>
    sys.exit(main())
  File "main.py", line 1803, in main
    app = GUI()
  File "main.py", line 770, in __init__
    common.preview = Preview()
  File "main.py", line 92, in __init__
    create_thumbnails(common.settings.src_path)
  File "/usr/lib/python3.8/site-packages/azote/tools.py", line 446, in create_thumbnails
    for in_path in glob.glob(os.path.join(scr_path, "*.{}".format(extension))):
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - WM: sway 1.5
 - Kernel: 5.7.11-arch1-1
 - GTK3:  3.24.21-1
 - GTK2: 2.24.32-2
 - GDK-pixbuf2: 2.40.0+6+g5432316df-1
 - Wayland: 1.18.0-2
 - XWayland: 1.20.8-3

**Azote version (please state it clearly if you use -git version):**
1.7.12-1 stable

**Additional context**
Debugging the code a bit I see that `src_path` is completely empty from the start, here is the result of `vars(common.settings)`

```
{
    'file': '/home/oscarcp/.local/share/azote/settings.pkl',
    'src_path': None,
    'sorting': 'new',
    'custom_display': None,
    'old_thumb_width': 240,
    'clear_thumbnails': False,
    'copy_as':'#rgb',
    'color_dictionary': False,
    'image_menu_button': False,
    'track_files': True,
    'rc_file': '/home/oscarcp/.config/azote/azoterc',
    'thumb_width': 240,
    'thumb_height': 135,
    'thumb_size': (240, 135),
    'columns': 3,
    'color_icon_w': 100,
    'color_icon_h': 50,
    'clip_prev_size': 30,
    'palette_quality': 10,
    'tracking_interval_seconds': 5
}
```

**Comment by nwg-piotr** [comment]
- Have you by any chance deleted or renamed the folder you store wallpapers in lately?
- could you try deleting or renaming the `~/.local.share/azote/settings.pkl` file?

**Comment by oscarcp** [comment]
>     * Have you by any chance deleted or renamed the folder you store wallpapers in lately?

Nope. Always has been `~/Pictures/wallpapers`

>     * could you try deleting or renaming the `~/.local/share/azote/settings.pkl` file?

I did that, now it works, it takes  `/usr/share/backgrounds/sway` as the default. Thanks!

**Comment by nwg-piotr** [comment]
Well, this should be handled in the code. I'll add add a patch anyway. Thanks for reporting.
