### ISSUE TITLE
Repository signature is invalid

### ISSUE THREAD

**Issue by luispabon** [nwg-piotr/azote#104]
**Describe the bug**
Looks like the signature for the apt repo in ubuntu has expired.

**To Reproduce**
```
~ sudo apt update
[...]
Err:10 http://download.opensuse.org/repositories/home:/Head_on_a_Stick:/azote/xUbuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG A0E2FC066309A9C9 home:Head_on_a_Stick OBS Project <home:Head_on_a_Stick@build.opensuse.org>
```

**Expected behavior**
It works.

**Desktop (please complete the following information):**
 - Linux distribution: Ubuntu 20.04
 - WM: Sway

**Azote version (please state it clearly if you use -git version):**
n/a

**Additional context**
n/a

**Comment by nwg-piotr** [comment]
We can only ask the maintainer for help: @Head-on-a-Stick

**Comment by Head-on-a-Stick** [comment]
See https://forum.archlabslinux.com/t/azote-wallpaper-manager/3329/404?u=head_on_a_stick

**Comment by luispabon** [comment]
Thank you :+1:
