### ISSUE TITLE
The right half of the app is unresponsive in floating mode.

### ISSUE THREAD

**Issue by snakedye** [nwg-piotr/azote#109]
**Describe the bug**

The half of the app becomes unresponsive when it's in floating mode and the right border is set in the middle.

**To Reproduce**
1. Launch Azote
2. Put it in floating mode

**Expected behavior**
The entire app should be responsive and the border should cross it in the middle.

**Screenshots**
![image](https://user-images.githubusercontent.com/49378990/93669344-88ac8200-fa61-11ea-8738-427391d8ea06.png)

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - WM: sway

**Azote version (please state it clearly if you use -git version):**
 - v1.7.14

**Additional context**

**Comment by nwg-piotr** [comment]
It happens when the window goes full screen and back. In principle, Azote should not be full screened. Check your config. If it happens, however, you need to click a wallpaper miniature on the left side, and all the window should be accessible again.

**Comment by snakedye** [comment]
https://youtu.be/d7IMywCf8do

**Comment by nwg-piotr** [comment]
On sway, when no additional rules applied, Azote should start like this:

![image](https://user-images.githubusercontent.com/20579136/93691184-33648500-fae2-11ea-963e-fbd125319c4d.png)

**Comment by snakedye** [comment]
What do you mean by no additional rules? Windows are tiled by default. I don't have any command for azote in my [config](https://github.com/snakedye/sway_config/blob/master/sway/config).

**Comment by nwg-piotr** [comment]
You may test the commit above by installing `azote-git`. No additions to config required.

**Comment by snakedye** [comment]
It does startup in floating mode but the effect described in the screenshot still persists.
![image](https://user-images.githubusercontent.com/49378990/93712632-12715380-fb25-11ea-9d3c-ae0ec5ee8191.png)

**Comment by nwg-piotr** [comment]
Initially it should display 3 columns, unless you maximized it earlier, or specified `"columns": "6"` in `~/.config/azote/azoterc`.

```
{
  "thumb_width": "240",
  "columns": "3",
  "color_icon_w": "100",
  "color_icon_h": "50",
  "clip_prev_size": "30",
  "palette_quality": "10",
  "tracking_interval_seconds": "5"
}
```

**Comment by snakedye** [comment]
`"columns": "3"`

That solved the issue
