### ISSUE TITLE
Azote crashes if a display is connected but not enabled.

### ISSUE THREAD

**Issue by dpgeekzero** [nwg-piotr/azote#110]
https://github.com/nwg-piotr/azote/blob/90eafb6fc885cd67cc251351149c5973255c6372/azote/tools.py#L149

I technically have 4 monitors connected, but one of them is turned off (xrandr --output eDP-1-1 --off).

```
❯ xrandr | grep ' connected'
eDP-1-1 connected (normal left inverted right x axis y axis)
DP-1-3 connected 640x480+7680+0 (normal left inverted right x axis y axis) 708mm x 398mm
DP-1-1-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 609mm x 349mm
DP-1-1-2 connected 3840x2160+3840+0 (normal left inverted right x axis y axis) 600mm x 340mm
```

Azote crashes with an error every time:

```
❯ azote 
Traceback (most recent call last):
  File "main.py", line 1814, in <module>
    sys.exit(main())
  File "main.py", line 1799, in main
    set_env(lang)  # detect displays, check installed modules, set paths and stuff
  File "/usr/lib/python3.8/site-packages/azote/tools.py", line 289, in set_env
    common.displays = check_displays()
  File "/usr/lib/python3.8/site-packages/azote/tools.py", line 155, in check_displays
    w_h = res[i].split('x')
IndexError: list index out of range
```

**Comment by dpgeekzero** [comment]
Pretty sure this is the same as the AUR issue reported here: https://aur.archlinux.org/packages/azote/#comment-755010

**Comment by dpgeekzero** [comment]
Simple diff for using i3-msg, doesn't actually fix my problem as feh has the same issue.  It takes the first image and applies it to the disconnected display.

I really miss sway, it's a shame zoom doesn't work right.  :(

`diff --git a/azote/tools.py b/azote/tools.py
index ae69ff9..e2748bc 100644
--- a/azote/tools.py
+++ b/azote/tools.py
@@ -67,6 +67,8 @@ def check_displays():
             common.env['wm'] = os.getenv('XDG_SESSION_DESKTOP')
         elif os.getenv('DESKTOP_SESSION'):
             common.env['wm'] = os.getenv('DESKTOP_SESSION')
+        elif os.getenv("I3SOCK"):
+            common.env['wm'] = "i3"
         else:
             common.env['wm'] = 'not sway'
 
@@ -144,6 +146,21 @@ def check_displays():
         displays = sorted(displays, key=lambda x: (x.get('x'), x.get('y')))
         return displays
 
+    elif common.env["wm"] == "i3":
+        outputs = json.loads(subprocess.check_output("i3-msg -t get_outputs", shell=True).decode('utf-8'))
+        names = [x.get("name") for x in outputs if x.get("active")]
+        res = [x.get("rect") for x in outputs if x.get("active")]
+        displays = []
+        for i in range(len(names)):
+            display = {'name': names[i],
+                       'x': res[i].get("x"),
+                       'y': res[i].get("y"),
+                       'width': res[i].get("width"),
+                       'height': res[i].get("height")}
+            displays.append(display)
+            log("Output found: {}".format(display), common.INFO)
+        return displays
+
     # On i3 we could use i3-msg here, but xrandr should also return what we need. If not on Sway - let's use xrandr
     elif common.env['xrandr']:
         names = subprocess.check_output("xrandr | awk '/ connected/{print $1}'", shell=True).decode(`

**Comment by nwg-piotr** [comment]
If you're on Arch, you could install `azote-git` to check if it helps.

**Comment by nwg-piotr** [comment]
> I really miss sway, it's a shame zoom doesn't work right.

Judging from [the issue](https://github.com/nwg-piotr/nwg-launchers/issues/111) (resolved) submitted to my other project, people use Zoom on sway. :)

**Comment by dpgeekzero** [comment]
> If you're on Arch, you could install `azote-git` to check if it helps.

Yup!  That works.  Thanks!

**Comment by nwg-piotr** [comment]
Excellent. I'll publish a new release as soon as at least one more issue is resolved. Thanks for reporting the bug.
