### ISSUE TITLE
Screen turns black when the app launch

### ISSUE THREAD

**Issue by snakedye** [nwg-piotr/azote#129]
**Describe the bug**
Screen turns black when the app launch

**To Reproduce**
1. Launch Azote

**Expected behavior**
Screen stays normal
https://drive.google.com/file/d/1fBueUR14N_AKwE0VoWprMygxctfQ_QGB/view?usp=sharing

**Screenshots**

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - WM: sway

**Azote version (please state it clearly if you use -git version):**
 - 1.8.0 git version

**Additional context**

**Comment by nwg-piotr** [comment]
https://github.com/nwg-piotr/azote/releases/tag/v1.8.0

> Since Gdk.Screen.height has been deprecated, there's no reasonable way to determine the screen dimensions. We need to open a temporary window, maximize it, and measure its height to open the Azote window with maximum allowed vertical dimension. In ~/.config/azote/azoterc you'll find the "screen_measurement_delay": "300" value. Different hardware and window managers need different time to open the temporary window. Increase the value if the (floating) window does not scale to the screen height. Decrease as much as possible to speed up launching Azote.

On sway we need to use .fullscreen() instead of .maximize(). Fullscreened windows on sway are always 100% opaque. Decrease the default 300 ms as much as possible in order not to see the artifact.

**Comment by snakedye** [comment]
I dropped "screen_measurement_delay" to 10 and it fixed the issue.

**Comment by nwg-piotr** [comment]
Or at least hid it. :) Sorry, it seems too be no better way at the moment: https://stackoverflow.com/questions/64038301/how-to-check-the-current-screen-dimensions-in-python-gtk-3-0-without-deprecati

**Comment by nwg-piotr** [comment]
Suddenly I realised, that on sway I don't need to measure the screen height, as it's already known. Merged into master, will be released soon.
