### ISSUE TITLE
gtk3 dependency needed

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/azote#13]
Raised by [HoaS on AUR](https://aur.archlinux.org/packages/azote/#news):

> I think you need to add gtk3 as a depends, the program fails otherwise:

```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by Head-on-a-Stick** [comment]
Yeah, that was me :-)

I thought the AUR was a better place to raise the issue because this repository doesn't contain a PKGBUILD any more.

**Comment by nwg-piotr** [comment]
Right. Just wanted to gather all issues in one place. It's easy to forget something in my 50's. :)

**Comment by nwg-piotr** [comment]
Added in PKGBUILD 0.1.1-2
