### ISSUE TITLE
[python 3.9] No Such File or Directory

### ISSUE THREAD

**Issue by xtariq** [nwg-piotr/azote#136]
Hi. 

I'm pretty new to posting issues on Github.

I have used Azote for months and it worked perfectly. Today something happened where it says the following and doesn't start.

`/usr/bin/azote: line 4: cd: /usr/lib/python3.9/site-packages/azote: No such file or directory
/usr/bin/python3: can't open file '/home/user/main.py': [Errno 2] No such file or directory`

Any help would be greatly appreciated.

**Comment by nwg-piotr** [comment]
You received python upgrade, and the lib path had been changed. Installing autotiling again should help.

**Comment by xtariq** [comment]
Thank you for your response.

I downloaded autotiling-1.1-1 via yay. I then ran Azote from the terminal and received the same error. Any other suggestions are much appreciated.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nwg-piotr** [comment]
I haven't uses yay ever in my life, but it should install in the proper location. If it doesn't, try uninstalling and installing again.

**Comment by xtariq** [comment]
Thanks again for your response. I uninstalled and reinstalled multiple times.

What's interesting is that I still see the old Azote wallpaper even though I can't open the program.

Perhaps this information is useful. Thanks again.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nwg-piotr** [comment]
Shit, did I say "autotiling"? Surely you need to reinstall the azote package. :D Sorry, I was just waking up.

**Comment by xtariq** [comment]
No worries! :)

I installed autotiling, and then uninstalled and reinstalled the azote package.

I think the issue is something with Python, but I don't know enough about it to understand what is going on -_-

Best,
Tariq

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nwg-piotr** [comment]
What is should look like:

the

`$ LIB=$( python3 -Ic "from distutils.sysconfig import get_python_lib; print(get_python_lib())" ) ; echo $LIB`

command should return

`/usr/lib/python3.9/site-packages`

After you reinstalled, azote should be placed in `/usr/lib/python3.9/site-packages/autotiling/`, but it seems to be still in `/usr/lib/python3.8/site-packages/autotiling/`. Could you take a look at these directories and confirm?

**Comment by xtariq** [comment]
The command returns the correct answer.

I uninstalled again (maybe 7th time?) and reinstalled, and it worked! I don't know what happened. Maybe something with the autotiling. Thanks so much for you help.

Next, to figure out nwg customizations. Everything is amazing. Thanks again

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nwg-piotr** [comment]
Excellent!

BTW: I've just done everything as above on my testing laptop, untouched for 3 days, and it went well at the first attempt. TBH: I should bump version of all my python packages to force updates (for some reason bumping just the revision number doesn't help), but it would require a new release for each one. Maybe in the evening I will take this ungrateful job. :D Every major python upgrade is PITA.

**Comment by nwg-piotr** [comment]
Closing, as it seems to be no longer an issue.
