### ISSUE TITLE
It doesn't launch on River

### ISSUE THREAD

**Issue by snakedye** [nwg-piotr/azote#137]
**Describe the bug**
swaybg works just fine on River but azote doesn't launch.

**To Reproduce**
1. Launch river
2. Try to launch azote

**Expected behavior**
Azote should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/49378990/103172808-1e576a80-4824-11eb-9c13-13ca6ecc4970.png)

**Desktop (please complete the following information):**
 - Linux distribution: EndeavoursOS
 - WM: river

**Azote version (please state it clearly if you use -git version):**
azote-git 1.7.14.r17.g76607a2-3

**Comment by nwg-piotr** [comment]
As in the picture: install the `wlr-randr` package and try again.

**Comment by snakedye** [comment]
I already have wlr-randr installed

**Comment by nwg-piotr** [comment]
Well, I'd have to install River and find a solution. For now it's unsupported.

**Comment by nwg-piotr** [comment]
@snakedye Do you by any chance know if River has a command that returns outputs names and geometry? If not, we'll be unable to support multi-headed setups.

**Comment by snakedye** [comment]
I'm not aware of such a command but I don't see any reason why it wouldn't be possible to interface directly with the compositor using a wlroots protocol (wlr-output-management) . wldisplays for example can get outputs names and geometry from  wlroots compositors.

![image](https://user-images.githubusercontent.com/49378990/104108504-2fc45c00-5293-11eb-80e6-3711f87a8d05.png)

**Comment by nwg-piotr** [comment]
wlr-randr does the same, and should work on any wlroots-based compositor. Dunno why it doesn't work here.

**Comment by snakedye** [comment]
I tried Azote right now on river and it works.

**Comment by nwg-piotr** [comment]
Which version?

**Comment by snakedye** [comment]
azote-git 1.8.1.r8.g0f8ae39-2

**Comment by nwg-piotr** [comment]
Very well, thanks. I think it's time to release 1.8.2. The current release misses some bug fixes.
