### ISSUE TITLE
Segmentation fault on release and master versions

### ISSUE THREAD

**Issue by Fogapod** [nwg-piotr/azote#152]
**Describe the bug**

```sh
$ python azote/main.py
[1]    71532 segmentation fault (core dumped)  python azote/main.py
```

**To Reproduce**
1. use azote with any arguments or without: `$ azote` `$ azote --version` `$ python azote/main.py`

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - WM: i3, xorg

**Azote version (please state it clearly if you use -git version):**
 - latest release and master branch

**Comment by Fogapod** [comment]
This line is causing segfault: <https://github.com/nwg-piotr/azote/blob/9464764728028c4a8ce604ef6366f990fc6db2a0/azote/tools.py#L17>
Adding `import sys;sys.exit(1)` in front of it stops segfaults.
Looks like it's not azote issue.

Though this works:
```python
$ python
Python 3.9.6 (default, Jun 30 2021, 10:22:16)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image, ImageOps
>>>
```

**Comment by nwg-piotr** [comment]
Are you sure you haven't installed the PIL library with `pip install pil`?

**Comment by Fogapod** [comment]
What do you mean? I have `Pillow` installed.
```python
from PIL import __version__
>>> print(__version__)
8.3.1
```

**Comment by nwg-piotr** [comment]
python-pillow is a  fork of the PIL library which we need. PIL is in conflict with python-pillow.

**Comment by Fogapod** [comment]
I don't use old 2006 library as I shown in previous message

**Comment by nwg-piotr** [comment]
Well, no idea at the moment. Works for me as well on sway, as X11. Since it dies for you that early, I suppose you have nothing in `~/.local/share/azote/log.txt`?

**Comment by Fogapod** [comment]
No, nothing, since it dies on import phase, not even getting to `main()`

**Comment by Fogapod** [comment]
So this sequence of imports reliably produces segfault for me:
```python
import gi
from PIL import Image
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, GdkPixbuf, Gdk, GLib
from PIL import Image, ImageOps
```

**Comment by nwg-piotr** [comment]
BTW: ImageOps seems to be unnecessary. I'll check again to make sure, but it seems I should delete it.

**Comment by Fogapod** [comment]
Yeah, they are not used. Removing ImageOps fixes issue for me

**Comment by nwg-piotr** [comment]
Very well. I'll remove them.
