### ISSUE TITLE
Make azote work with swaylock somehow

### ISSUE THREAD

**Issue by wildwestrom** [nwg-piotr/azote#160]
I would love if azote could set the background for `swaylock`.

Currently I have my swaylock config like this:
```
image=/full/path/to/image.png
scaling=fit
color=000000
```

Ideally I'd like to see:
1. `swaylock` detected if present on the system.
2. A GUI option to add a specific background just for the lockscreen.
3. Make it so the swaylock config can stay the same upon changing the wallpaper.

Since `swaylock`'s config lives in `$XDG_CONFIG_HOME/swaylock/config`, the `image` setting could point to a specific directory or symbolic link to the image, which azote handles. A solution like this would allow one to not "hard-code" the image within the swaylock config for version control purposes.

**Comment by nwg-piotr** [comment]
It could be done, but we have to think carefully about it. The solution should be universal enough so that it could work not with swaylock only. Sorry, but this must wait a little bit. I have a lot of feature requests and bug reports in all my projects, but hardly any contributions.

**Comment by rs-pro0** [comment]
What about making some file like .azoteimage and make it a symlink to current wallpaper. Then you just specify it as swaylock image.

**Comment by nwg-piotr** [comment]
I put quite a lot of effort in the lock screen management in the nwg-shell config utility. It works on sway, and will work on Hyprland soon. One can choose random images from unsplash.com, and from a local path. Let me be honest: if I'm going to add an option to choose one certain image, I'll do it in nwg-shell as well. I don't have enough spare time to implement stuff that's not going to be useful in my flagship project, sorry.

![image](https://user-images.githubusercontent.com/20579136/232205743-20d428d1-77d4-4da3-94ef-fe5dacc4508c.png)

**Comment by rs-pro0** [comment]
I think I could implement my solution this but I'm not sure if it is the solution you want. I'll check out your config utility and maybe I'll come up with something better.
