### ISSUE TITLE
`KeyError: 'generic-name'` when trying to set wallpaper from an image

### ISSUE THREAD

**Issue by hochata** [nwg-piotr/azote#162]
**Describe the bug**
After trying to set a wallpaper from an image,  nothing visibly happens. The stacktrace shows the following

```shell
Running on Wayland, but not sway
Available screen height: 708 px; measurement delay: 300 ms
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/azote/main.py", line 461, in on_apply_button
    display_name = item["generic-name"]
KeyError: 'generic-name'
```

**To Reproduce**
1. Open Azote
2. Select an image
3. Click on the button to try to set the selected image as a wallpaper

**Expected behavior**
To have the wallpaper properly set.

**Desktop:**
 - Linux distribution: Artix Linux
 - WM: riverwm

**Azote version:**
 - v1.9.3

**Additional context**
I've mostly used Sway and there Azote works perfectly. I was just trying River and noticed this issue.

It seems using colors directly works just fine.

**Comment by nwg-piotr** [comment]
Could you uncheck the "Use generic display names" box and tell me if it helps?

![image](https://user-images.githubusercontent.com/20579136/170863367-2c6cbaec-c9bc-4e93-af67-6f4749efb012.png)

**Comment by nwg-piotr** [comment]
Closed unintentionally, sorry. But this should fix the issue. Tested on Wayfire, as my river died.

**Comment by hochata** [comment]
Unchecking the `Use generic display` option does solve the issue.

Thanks for the very fast response!

**Comment by nwg-piotr** [comment]
It should work now with "Use generic display", too.

**Comment by hochata** [comment]
Yep, with the new release it works without untoggling anything. Thanks!
