### ISSUE TITLE
Animated wallpapers

### ISSUE THREAD

**Issue by Iss-in** [nwg-piotr/azote#167]
I am a huge fan of wallpaper engine linux, would love to see if this project will be able to mimic some of the functionality :)

1. be able to allow videos as wallpapers. Since mpvpaper already exist, it will be awesome to merge the feature in this project . 

2. If possible, since kde already has a plugin for wallpaper engine, this can be implemented as well :)

**Comment by nwg-piotr** [comment]
This project is a frontend to swaybg & feh, with some GUI to browse and manipulate images. It has no engine, and was not intended to have one. What you want, is another program, which, to be honest, I'm not interested in, sorry.
