### ISSUE TITLE
Regression: .azotebg broken due to #166

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/azote#169]
Applying changes to the default .azotebg file provided by nwg-shell results in strange file content.

```bash
#!/usr/bin/env bash
pkill swaybg
swaybg -o 'Goldstar Company Ltd  0x00002B47' -i "/home/piotr/Obrazy/Wallpapers/badkarma-headphones2.jpeg" -m fill &
swaybg -o 'Iiyama North America PLT2336 11233G4600070' -i "/home/piotr/Obrazy/Wallpapers/badkarma-headphones2.jpeg" -m fill &
killall swaybg 2>/dev/null
swaybg -o '*' -i '/usr/share/backgrounds/nwg-shell.jpg'
```

Furthermore, if we check/uncheck "Use generic output names", we end up in even more trash content.

```bash
#!/usr/bin/env bash
pkill swaybg
swaybg -o 'DVI-I-1' -i "/home/piotr/Obrazy/Wallpapers/badkarma-springs.jpeg" -m fill &
swaybg -o 'DP-2' -i "/home/piotr/Obrazy/Wallpapers/badkarma-springs.jpeg" -m fill &
swaybg -o 'Goldstar Company Ltd  0x00002B47' -i "/home/piotr/Obrazy/Wallpapers/badkarma-headphones2.jpeg" -m fill &
swaybg -o 'Iiyama North America PLT2336 11233G4600070' -i "/home/piotr/Obrazy/Wallpapers/badkarma-headphones2.jpeg" -m fill &
killall swaybg 2>/dev/null
swaybg -o '*' -i '/usr/share/backgrounds/nwg-shell.jpg'
```

In order to #166, we must not rely on the .azotebg file content.

For some reason, still a bit mysterious to me, it also hangs Azote after pressing the "Apply" button.

@emanuelserpa - I'm about to revert #166

**Comment by emanuelserpa** [comment]
Hi.

Yeah, there are shortcomings with #166, clearly.

It just verifies if the display is present in the file and changes the text only in the changed displays. An exception could be added for '*' outputs and if generic output names are used the file would be cleared.

But yeah, it is not an optimal resolution.

>For some reason, still a bit mysterious to me, it also hangs Azote after pressing the "Apply" button.

Mysterious for me, too, because I don't experience any hang.

**Comment by nwg-piotr** [comment]
> Mysterious for me, too, because I don't experience any hang.

It seems to only happen if one starts from the default nwg-shell .azotebg file.
