### ISSUE TITLE
Cant run azote

### ISSUE THREAD

**Issue by its-ag** [nwg-piotr/azote#171]
**Describe the bug**
Azote command is not working.

**To Reproduce**
- Run ``azote`` either from terminal.

**Expected behavior**
It should open the application.

**Screenshots**
![2023-01-24T11:12:11,772261614+05:30](https://user-images.githubusercontent.com/102473837/214220502-5fb5c15a-64b6-42e2-be4b-ef410d444bbd.png)

**Desktop (please complete the following information):**
 - Linux distribution: Garuda Linux (Arch Based)
 - WM: sway

**Azote version (please state it clearly if you use -git version):**
 - version number from the "About" window (Cant get the windows opened)

**Comment by nwg-piotr** [comment]
Do you run Azote with the `-l` argument? What does `echo $LANG` return for you?

**Comment by nwg-piotr** [comment]
Closing due to no further feedback.
