### ISSUE TITLE
cannot use "Split selection between displays"

### ISSUE THREAD

**Issue by Appel-flappen** [nwg-piotr/azote#179]
**Describe the bug**
I am attempting to use Azote to split a wallpaper over my 2 monitors. (1 landscape, 1 portrait). When I select my wallpaper and use the split selection button, azote closes.

**To Reproduce**
1. launch Azote with azote -l en_US (no lang for en_GB)
2. click on my desired wallpaper
3. click on split slection...
4. hangs for a few seconds
5. crashes

full output of console:
```
$ azote -l en_US
Running on sway
Available screen height: 1824 px
Gdk-Message: 19:21:49.375: Lost connection to Wayland compositor.
```

**Expected behavior**
applying wallpaper works over multiple displays, _a la_ superpaper

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - WM: sway

**Azote version (please state it clearly if you use -git version):**
 - v1.11.0

**Additional context**
Using nvidia proprietary drivers and fixes from sway-nvidia package.

**Comment by nwg-piotr** [comment]
Sorry, but I won't be able to help. The `Lost connection to Wayland compositor` message appears after errors happening outside my code. I haven't used nvidia for years, so dunno even where to start from.

**Comment by Appel-flappen** [comment]
Ah, I see. Thanks for the quick response. Do you know any way to get a bit more debugging information so I can investigate further?

**Comment by nwg-piotr** [comment]
You may try reading the `~/.local/share/azote/log.txt` file, though I don't think it's going to help much.
