### ISSUE TITLE
Monitor identifiers wrong/reversed

### ISSUE THREAD

**Issue by FluffBallFloof** [nwg-piotr/azote#185]
Azote is attaching the wrong identifiers to my monitors

Left monitor should be my HDMI-0 the 1920x1200 one, right is the vertical VGA-0 1080x1920

Fedora rawhide with i3

happening on version 1.12.3

![image](https://github.com/nwg-piotr/azote/assets/39450493/a7018ba1-fc43-47dc-ae00-6cebe087d871)

Sorry I don't really have much info, I'm not sure why it's IDing them wrong.

**Comment by nwg-piotr** [comment]
Which compositor or WM do you run Azote on?

**Comment by FluffBallFloof** [comment]
i3wm, annoyingly I don't have that monitor config anymore so I can't really do much troubleshooting without dragging my PC across the house. Finally bought a fresh pair of monitors.

**Comment by nwg-piotr** [comment]
Congrats! ;) I haven't used i3 (nor any other X11 stuff) for at least 2 years now, so it would be difficult as hell to debug this issue on my side. Do you think it could be closed?

**Comment by FluffBallFloof** [comment]
Probably, my current monitor config doesn't have this issue so it isn't worth chasing down.
