### ISSUE TITLE
Enable "Discussions" for github

### ISSUE THREAD

**Issue by 01micko** [nwg-piotr/azote#195]
**Is your feature request related to a problem? Please describe.**
No it is not. "Discussions" is just a github feature

**Describe the solution you'd like**
Enable Discussions :)

**Describe alternatives you've considered**
Using an issue, but why clutter issues with nefarious junk which may however be useful to other users.

**Additional context**
I got `azote` working on debian/trixie/testing and perhaps other users would like to know how I did it. It's a bit rough because I haven't got the menu entry working _but_ I did build a compliant debian package to install on my system using `debuild`, with quite a few warnings but it built, installed and runs without error.

#### screencap
![20240613_20h33m45s_grim](https://github.com/nwg-piotr/azote/assets/1019119/b889feaa-0e2f-470a-9f39-ddd67dd6db9f)

Thanks for consideration and thanks for `azote`!

EDIT to add: As you may know I'm using `labwc` :)

**Comment by nwg-piotr** [comment]
Well, I'm not sure if I want to enable discussions on separate repos. This may cause a mess difficult to control. Could you just use [nwg-shell Discussions](https://github.com/nwg-piotr/nwg-shell/discussions)?

**Comment by 01micko** [comment]
Ok, soumds like a plan!
