### ISSUE TITLE
only a small subset of the thumbnails gets created

### ISSUE THREAD

**Issue by hariseldon78** [nwg-piotr/azote#197]
**Describe the bug**
Most images don't get a thumbnail, only the "document" icon:

**To Reproduce**
- open app
- feel the sadness

**Screenshots**
![image](https://github.com/user-attachments/assets/2a2d9c35-d1c6-4dae-8d00-e47524ef71fe)

**Desktop (please complete the following information):**
 - Linux distribution: Arch linux
 - WM: Hyprland

**Azote version (please state it clearly if you use -git version):**
 - v1.13.0

**Additional context**
I imagine the problem is coming from some gtk library, happy to report the versions and install git version if that could help

**Comment by nwg-piotr** [comment]
Some images (far from majority) refuse to get scaled with the imagemagick library. To find out whether this is the case, try opening an image with GIMP and saving under another filename (to trigger thumbnail creation).

**Comment by hariseldon78** [comment]
Unfortunately it doesn't help. It surely must be something in my system, can you suggest some way to debug it?
One thing i see is that when it's creating the thumbnails there is a long list of these errors on the console: 
```
(azote:697992): Gtk-WARNING **: 00:16:26.274: Tried to remove non-child 0x5f58628ba970

(azote:697992): Gtk-WARNING **: 00:16:26.275: Tried to remove non-child 0x5f5861805fc0

(azote:697992): Gtk-WARNING **: 00:16:26.275: Tried to remove non-child 0x5f586260dc00

(azote:697992): Gtk-WARNING **: 00:16:26.275: Tried to remove non-child 0x5f586078ee10
```

I attach here one of the failing images, but i promise: 95% of my images doesn't get a thumbnail.
I tried to open - export it from gimp, also tried editing it, scaling it, and saving on another name. I tried playing with the png and jpg exporting options, but nothing is working.
![frog4](https://github.com/user-attachments/assets/f669cc45-ec0a-4a7e-ad62-1a6057daf08d)
![frog3](https://github.com/user-attachments/assets/97346b3a-eee0-4183-90be-4936d339387b)
![frog2](https://github.com/user-attachments/assets/6d781b1b-c124-4e81-b457-4e3b23839052)

**Comment by hariseldon78** [comment]
I also tried rebuilding the imagemagick package, using the imagemagick-full variant this time

**Comment by nwg-piotr** [comment]
Well, azote installed from the arch package refuses to create a half of thumbnails out of my images. In the same time azote running from PyCharm creates thumbnails with no error. I'll take a closer look at it.

**Comment by nwg-piotr** [comment]
May I see your `~/.local/share/azote/log.txt`?

**Comment by hariseldon78** [comment]
> May I see your `~/.local/share/azote/log.txt`?

[log.txt](https://github.com/user-attachments/files/17122273/log.txt)

**Comment by hariseldon78** [comment]
> May I see your `~/.local/share/azote/log.txt`?

[log.txt](https://github.com/user-attachments/files/17122305/log.txt)

**Comment by nwg-piotr** [comment]
Thank you. It's a bug. Fix on the way.

**Comment by nwg-piotr** [comment]
Fixed. Thank you for reporting.
