### ISSUE TITLE
Animated wallpapers

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/azote#199]
Is implementation for animated wallpapers a possibility?

**Comment by nwg-piotr** [comment]
What exactly do you mean? Video files or images changing over time?

**Comment by hecto600** [comment]
Support for short videos like .gif or .mp4 such as this one below:
![city](https://github.com/user-attachments/assets/367a46e2-b6fa-4320-9f7d-b0050913c382)

**Comment by nwg-piotr** [comment]
Well, this program is actually just a frontend to swaybg. It could display gifs, but without animation. We would need something else to display animated gifs and/or mp4 files.

**Comment by hecto600** [comment]
I tried to request animation support in swaybg repo but they said it was out of scope and sent me a list of addons https://github.com/swaywm/sway/wiki/Useful-add-ons-for-sway#wallpaper highlighting `swww` and `mpvpaper` for this. Is any of these addons integration useful?
