### ISSUE TITLE
Could Azote save a script to reapply the background (like .fehbg)?

### ISSUE THREAD

**Issue by dpgeekzero** [nwg-piotr/azote#24]
When I use feh directly to set a wallpaper, it saves a script to my home directory called .fehbg, which I can run in my startup scripts so that my wallpaper change persists.

Could Azote do something similar, writing a script that runs whatever tool it is using to set the wallpaper?

Thanks for the great app!

**Comment by dpgeekzero** [comment]
Sorry, I guess I can't read.

**Comment by nwg-piotr** [comment]
Haha! You were fast enough for me not to notice the issue at all. :)
