### ISSUE TITLE
Allow setting one wallpaper to all outputs

### ISSUE THREAD

**Issue by luispabon** [nwg-piotr/azote#29]
The way I usually set wallpapers is one wallpaper for all outputs. With the current setup, azote generates one swaybg call per display output. Example below when I have no external displays:

```
#!/usr/bin/env bash
pkill swaybg
swaybg -o eDP-1 -i /home/luis/Pictures/Wallpapers/ubuntu-wallpapers/ubuntustudio/ubuntustudio-default.png -m fill &
```
Which is good until I connect another display and is showing nothing but my default background 
```
output * bg ~/Pictures/backgrounds/kate-hazen-fractal-mountains.png fill
exec ~/.azotebg
```
I had to add my default background otherwise connecting another display shows a solid default colour that burns my retinas ;)

Anyhow, would it be possible to add an "all outputs" option? Could be, say, a checkbox that when checked hides the output buttons, and when unchecked shows them (as it is now).

Thank you!

**Comment by nwg-piotr** [comment]
Probably no problem, but it needs to be implemented for feh / X11 as well. Added to my todos, Thanks for feedback!

**Comment by nwg-piotr** [comment]
Resolved in v1.2.0

**Comment by luispabon** [comment]
Thank you, looking forward to the new .deb build to test it out :+1:

**Comment by nwg-piotr** [comment]
Haven't heard from @Head-on-a-Stick for a week. Hope he's alright, as I know nothing on packaging for Debian. :)
