### ISSUE TITLE
Folder selector does not respect current path

### ISSUE THREAD

**Issue by luispabon** [nwg-piotr/azote#30]
Right now, when tapping the button to bring up the folder selector for wallpapers, it opens the file dialog into "Recents". Would it be possible to make it open on the current selected folder instead?

**Comment by nwg-piotr** [comment]
It should be possible. I'll take a closer look at the issue tonight.

**Comment by nwg-piotr** [comment]
After https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html:

> Note that old versions of the file chooser’s documentation suggested using gtk_file_chooser_set_current_folder() in various situations, with the intention of letting the application suggest a reasonable default folder. This is no longer considered to be a good policy, as now the file chooser is able to make good suggestions on its own. 

It only needs 1 new code line to make the file chooser behave the way you requested, and it looks well to me. However, I wonder if this is what other users expect. Possibly this should be a user-configurable setting?

The change will be published in the nearest release.

**Comment by nwg-piotr** [comment]
Resolved in v1.2.0
