### ISSUE TITLE
Azote crashes when run

### ISSUE THREAD

**Issue by Wychmire** [nwg-piotr/azote#32]
This is on x86_64 Void Linux (non-musl)
I installed Azote successfully but whenever I try to run it (with `azote`) it crashes with the following message:

```
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
I didn't get this error when installing from the AUR when I was using Arch, but that was prior to your 1.2 release

**Comment by nwg-piotr** [comment]
Could you please install the `python3-setuptools` package and let me know if it changes anything?

**Comment by Wychmire** [comment]
It does indeed! After installing it launches properly.

**Comment by nwg-piotr** [comment]
My mistake: I shouldn't have removed it from dependencies. Will submit a revision to the package. Thanks for reporting!

**Comment by Wychmire** [comment]
np! Thanks for the quick solution, looking forward to the fixed template

**Comment by nwg-piotr** [comment]
[resolved](https://github.com/void-linux/void-packages/pull/12980)
