### ISSUE TITLE
2 crash maybe more bugs

### ISSUE THREAD

**Issue by HumanG33k** [nwg-piotr/azote#33]
I currently use debian testing with sway from ~unstable~ experimental .

Nothing special done 
```bash
python3 main.py 
Gdk-Message: 23:30:12.296: Lost connection to Wayland compositor
```

Try to open a directory with lot of pictures, more than 1800 Azote say 1864 but my terminal and thunar say 1857
```bash
python3 main.py 
Gdk-Message: 23:32:31.436: Error reading events from display: Broken pipe (pipe)
```
Next load thumb are here. 

When i try to refresh again (i do some other stuff)
```bash

python3 main.py 
Gdk-Message: 23:43:05.744: Window 0x21a7a020 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 23:43:05.744: Window 0x21a7a020 is a temporary window without parent, application will not be able to position it on screen.

(main.py:29826): Gdk-CRITICAL **: 23:43:05.764: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
2019-07-26 23:43:09 - [main.c:300] Found config * for output DP-2 ()
2019-07-26 23:43:09 - [main.c:300] Found config * for output DP-1 ()
Gdk-Message: 23:43:31.072: Window 0x1b2b8190 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 23:43:31.072: Window 0x1b2b8190 is a temporary window without parent, application will not be able to position it on screen.

(main.py:29826): Gdk-CRITICAL **: 23:43:31.097: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
2019-07-26 23:43:48 - [main.c:300] Found config DP-2 for output DP-2 ()
2019-07-26 23:43:48 - [main.c:296] Could not find config for output DP-1 ()
2019-07-26 23:43:48 - [main.c:296] Could not find config for output DP-2 ()
2019-07-26 23:43:48 - [main.c:300] Found config DP-1 for output DP-1 ()
Gdk-Message: 23:44:15.895: Lost connection to Wayland compositor.
```

The sort popup is too bottom on my screen and i can t show all option.
I’m not an gnome expert but buttons should not be on the top ? 

I absolutly not check dependancies but azote start well ;)

**Comment by nwg-piotr** [comment]
Well, I have no special experience if it comes to Debian, and especially to sway unstable. I only tested on buster + dwm, and it seemed to work well.

![2019-07-26-235632_1920x1080_scrot](https://user-images.githubusercontent.com/20579136/61983724-ccdcf780-b001-11e9-9d30-cc7a7c44ec9b.png)

Does the crash occur on this certain 1800+ files folder only, or on each another, too?

**Comment by Head-on-a-Stick** [comment]
> I currently use debian testing with sway from unstable.

The only official Debian package for `sway` is in the *experimental* repositories, is that what you mean? I have a version of `sway` built in a Debian bullseye chroot that is available in the `azote` Debian repository.

I've just triggered a rebuild for the testing/unstable `azote` & `sway` packages in my repository so perhaps try reinstalling those and see if you can still reproduce this.

FWIW, it can be tricky to support the Debian development branches because the various dependencies are not necessarily always synchronised.

**Comment by nwg-piotr** [comment]
I couldn't confirm the crash so far, too. However, I'll take a look if it makes sense to move the thumbnails creation to an asynchronous thread and avoid locking GUI.

**Comment by HumanG33k** [comment]
@Head-on-a-Stick  yes you are right it comes from experimental (i edit the first 

> FWIW, it can be tricky to support the Debian development branches because the various dependencies are not necessarily always synchronised.

I know that but i think it’s mostly because developpers are not aware of debian life cycle.

humm i think the error come from an other part i have a similar error with swaybg. 

I add a screenshot of azote on my second screen.

![screenshot](https://user-images.githubusercontent.com/1794193/61999085-0e30de00-b0ba-11e9-9dca-5774f203f70f.png)

**Comment by nwg-piotr** [comment]
Temporarily I'll leave the issue open, anyway. Creating thumbnails on an async thread seems an unnecessary complication, but possibly a progress bar would make sense.

**Comment by nwg-piotr** [comment]
v1.3.0 includes the progress bar, marking thumbnails creation process.
