### ISSUE TITLE
remove x11 dependencies for wayland users

### ISSUE THREAD

**Issue by AdrienLemaire** [nwg-piotr/azote#78]
Hi, and thank you for making and maintaining this awesome-looking package!

I've recently switched over to wayland and using sway WM. When trying to install azote from Arch User repositories, I noticed that it tries installing feh and xorg-xrandr, which won't be used. Can we maybe improve the PKGFILE to detect the current display server? Or have 2 distinct packages azote-x11 and azote-wayland ?

for the time being, I installed azote by editing PKGBUILD and removing `"feh" "xorg-xrandr"` before running `makepkg -si`

**Comment by nwg-piotr** [comment]
Hi,

As sircmpwn pointed out: [Developers shouldn't distribute their own software](https://drewdevault.com/2019/12/09/Developers-shouldnt-distribute.html).

The AUR package is tailored to my needs, as I test azote on sway and several other, X11-based WMs. People request separated packages for sway and not-sway, but it has nothing to do with the program development itself. 

It would be not bad to have 2 separate packages, including what's necessary and a selection of current optional dependencies for each environment. It would be even better if someone else could take care of those packages. :)

**Comment by Head-on-a-Stick** [comment]
> Can we maybe improve the PKGFILE to detect the current display server?

No, that's not possible because the packages are supposed to be buildable in a clean chroot, which wouldn't have Wayland or X running.

Adding `feh` & `xorg-xrandr` to the optdepends kinda makes sense given that `azote` is focused on Wayland desktops.

**Comment by nwg-piotr** [comment]
> Adding feh & xorg-xrandr to the optdepends kinda makes sense given that azote is focused on Wayland desktops.

Primary it used to be like this. Now it's important to me that it worked in both environments.
