### ISSUE TITLE
'Open with' function broken for files with spaces

### ISSUE THREAD

**Issue by bhepple** [nwg-piotr/azote#82]
'Open with' function is broken for files with spaces - eg try opening a file called 'My Holiday Snap.jpg'. Most programs like imv/feh simply fail quietly. Others like pinta show a file opening failure dialog for each word ie 'My', 'Holiday', 'Snap' etc so I suspect stronger quoting is required somewhere

**Comment by nwg-piotr** [comment]
Sure, it took 5 minutes. Sorry about the delay: I didn't receive any notification, neither looked into the project recently, being busy elsewhere.

**Comment by bhepple** [comment]
Cool. Thanks for the fix! New fedora package for new release 1.7.10 is built and anounced at https://www.reddit.com/r/Fedora/comments/fjaxoq/fedora_package_of_azote1710_is_available/

Bugzilla to track the progress into fedora at https://bugzilla.redhat.com/show_bug.cgi?id=1813737

**Comment by nwg-piotr** [comment]
Thanks for reporting the bug and all the packages. BTW: you could take a look at [this repository](https://github.com/nwg-piotr/nwg-launchers). I'm a newbie to C++, but sgtk-grid and bar versions coded in gtkmm seem to work well, and 2 times faster. At least on Arch...
