### ISSUE TITLE
Mention fedora?

### ISSUE THREAD

**Issue by bhepple** [nwg-piotr/azote#83]
Hi again, 

Sorry to be a nuisance, but you might want to mention Fedora in the initial description:

`The program is confirmed to work on sway, i3, Openbox, Fluxbox and dwm window managers, on Arch Linux, Void Linux, Debian and Fedora.`

Thanks for your patience!

**Comment by nwg-piotr** [comment]
Done. Thanks for cooperation! To be honest: I'm fed up with the C++ project I'm working on currently, looking forward to get back to python. :)
