### ISSUE TITLE
minor issue : python version needs to be bumped up to 3.8

### ISSUE THREAD

**Issue by ascesh** [nwg-piotr/azote#86]
Had to change 
`/usr/bin/azote`
to point to python3.8 to get azote working

```
cd /usr/lib/python3.8/site-packages/azote
```

am on fedora 32

uname -a                 
Linux ascesh-pc 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nwg-piotr** [comment]
I'm only the maintainer of AUR (Arch Linux) and Void packages. We need to ask @bhepple for help.

**Comment by bhepple** [comment]
I'll offer a patch to dist/azote which should fix up all these sorts of errors (and obviate the need for azote-arch etc??)

**Comment by bhepple** [comment]
A fixed fedora-32 version is building in koji (1.7.10-7) and will pop out of bodhi to the public servers in about a week or so.

**Comment by nwg-piotr** [comment]
Should be resolved for any Linux distro with #87
